/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NativeCallbackRouteImport } from './routes/native-callback'
import { Route as OauthReturnRouteImport } from './routes/oauth.return'
import { Route as ApiPublicOsAgentRouteImport } from './routes/api/public/os-agent'
import { Route as ApiPublicPushCronRouteImport } from './routes/api/public/push-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeCallbackRoute = NativeCallbackRouteImport.update({
  id: '/native-callback',
  path: '/native-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthReturnRoute = OauthReturnRouteImport.update({
  id: '/oauth/return',
  path: '/oauth/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOsAgentRoute = ApiPublicOsAgentRouteImport.update({
  id: '/api/public/os-agent',
  path: '/api/public/os-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushCronRoute = ApiPublicPushCronRouteImport.update({
  id: '/api/public/push-cron',
  path: '/api/public/push-cron',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/native-callback': typeof NativeCallbackRoute
  '/oauth/return': typeof OauthReturnRoute
  '/api/public/os-agent': typeof ApiPublicOsAgentRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/native-callback': typeof NativeCallbackRoute
  '/oauth/return': typeof OauthReturnRoute
  '/api/public/os-agent': typeof ApiPublicOsAgentRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/native-callback': typeof NativeCallbackRoute
  '/oauth/return': typeof OauthReturnRoute
  '/api/public/os-agent': typeof ApiPublicOsAgentRoute
  '/api/public/push-cron': typeof ApiPublicPushCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/native-callback'
    | '/oauth/return'
    | '/api/public/os-agent'
    | '/api/public/push-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/native-callback'
    | '/oauth/return'
    | '/api/public/os-agent'
    | '/api/public/push-cron'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/native-callback'
    | '/oauth/return'
    | '/api/public/os-agent'
    | '/api/public/push-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NativeCallbackRoute: typeof NativeCallbackRoute
  OauthReturnRoute: typeof OauthReturnRoute
  ApiPublicOsAgentRoute: typeof ApiPublicOsAgentRoute
  ApiPublicPushCronRoute: typeof ApiPublicPushCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-callback': {
      id: '/native-callback'
      path: '/native-callback'
      fullPath: '/native-callback'
      preLoaderRoute: typeof NativeCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/return': {
      id: '/oauth/return'
      path: '/oauth/return'
      fullPath: '/oauth/return'
      preLoaderRoute: typeof OauthReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/os-agent': {
      id: '/api/public/os-agent'
      path: '/api/public/os-agent'
      fullPath: '/api/public/os-agent'
      preLoaderRoute: typeof ApiPublicOsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push-cron': {
      id: '/api/public/push-cron'
      path: '/api/public/push-cron'
      fullPath: '/api/public/push-cron'
      preLoaderRoute: typeof ApiPublicPushCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NativeCallbackRoute: NativeCallbackRoute,
  OauthReturnRoute: OauthReturnRoute,
  ApiPublicOsAgentRoute: ApiPublicOsAgentRoute,
  ApiPublicPushCronRoute: ApiPublicPushCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
